# Generated by Django 5.1 on 2024-08-15 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='chatmessages',
            name='groupname',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='channel.groupname'),
            preserve_default=False,
        ),
    ]
