# Generated by Django 5.1 on 2024-08-15 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_groupname_chatmessages_groupname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessages',
            name='groupname',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='channel.groupname'),
        ),
    ]
