# Generated by Django 5.1 on 2024-08-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_alter_chatmessages_groupname'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupname',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
