# Generated by Django 5.1 on 2024-08-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_groupname_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupname',
            name='member_count',
            field=models.IntegerField(default=0),
        ),
    ]
