# Generated by Django 5.1 on 2024-08-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0005_groupname_member_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupname',
            name='member',
            field=models.TextField(blank=True),
        ),
    ]
