# Generated by Django 5.1 on 2024-08-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0007_alter_groupname_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupname',
            name='member',
            field=models.TextField(blank=True, default=''),
        ),
    ]
