# Generated by Django 5.1 on 2024-08-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0008_alter_groupname_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='file',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='chatmessages',
            name='message',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
