# Generated by Django 5.1 on 2024-08-16 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0009_chatmessages_file_alter_chatmessages_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessages',
            name='groupname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.groupname'),
        ),
    ]
