# Generated by Django 5.1 on 2024-08-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0010_alter_chatmessages_groupname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessages',
            name='file',
            field=models.FileField(blank=True, upload_to='images'),
        ),
    ]
