# Generated by Django 5.1 on 2024-08-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0011_alter_chatmessages_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessages',
            name='file',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
