# Generated by Django 5.1 on 2024-08-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0012_alter_chatmessages_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='message_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
