# Generated by Django 5.1 on 2024-08-17 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0013_chatmessages_message_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupname',
            name='last_active',
            field=models.TimeField(blank=True, default=datetime.datetime(2024, 8, 17, 20, 14, 35, 564590)),
        ),
    ]
