# Generated by Django 5.1 on 2024-08-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0013_chatmessages_message_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupname',
            name='last_active',
            field=models.CharField(blank=True, default=None),
        ),
    ]
