# Generated by Django 5.1 on 2024-08-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0016_alter_groupname_last_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupname',
            name='last_active',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
