# Generated by Django 5.1 on 2024-08-17 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0018_alter_groupname_last_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupname',
            name='last_active',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 17, 20, 54, 18, 28373)),
        ),
    ]
