# Generated by Django 5.1 on 2024-08-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0019_alter_groupname_last_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupname',
            name='last_active',
            field=models.CharField(blank=True, default='2024-08-18 04:43:39.951780', max_length=150, null=True),
        ),
    ]
